domain:
  method: XRD
  radiation: CuKa_double

measurement:
  range: [10.0, 100.0]
  step: 0.01
  holder_position: null
  impurity_cutoff: 0.0

simulation:
  n_patterns: 1000
  lattice_variation: 0.02
  intensity_variation: 0.05
  fwhm: 30
  background_ratio: 0.2
  noise_ratio: 0.03